import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import { db } from '@/lib/db/queries';
import { user } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { encode } from 'next-auth/jwt';

const ALLOWED_LOCALHOST_PORTS = ['3000', '3001'];

function isAllowedOrigin(referer: string | null): boolean {
  // Allow if referer is missing or stripped (e.g. window.open with noopener)
  if (!referer) return true;
  try {
    const url = new URL(referer);
    const hostname = url.hostname;
    const port = url.port;

    if (hostname === 'localhost' || hostname === '127.0.0.1') {
      return ALLOWED_LOCALHOST_PORTS.includes(port);
    }

    return hostname === 'myapps.ai' || hostname.endsWith('.myapps.ai');
  } catch {
    return false;
  }
}

export async function GET(request: NextRequest) {
  // 1. Enforce Referer origin check (only reject if referer is present but disallowed)
  const referer = request.headers.get('referer');
  if (!isAllowedOrigin(referer)) {
    console.warn(`[SSO] Rejected: invalid referer: ${referer}`);
    return NextResponse.json({ error: 'Access denied: invalid origin' }, { status: 403 });
  }

  // 2. Extract and validate the SSO token
  const ssoToken = request.nextUrl.searchParams.get('sso_token');
  if (!ssoToken) {
    return NextResponse.json({ error: 'Missing sso_token parameter' }, { status: 400 });
  }

  const parts = ssoToken.split('.');
  if (parts.length !== 2) {
    return NextResponse.json({ error: 'Invalid SSO token format' }, { status: 400 });
  }

  const [subject, signature] = parts;
  const subParts = subject.split(':');
  if (subParts.length !== 2) {
    return NextResponse.json({ error: 'Invalid SSO token subject' }, { status: 400 });
  }

  const [userId, issuedAtStr] = subParts;
  const issuedAt = parseInt(issuedAtStr, 10);
  if (!userId || isNaN(issuedAt)) {
    return NextResponse.json({ error: 'Invalid SSO token parameters' }, { status: 400 });
  }

  // Check token age (5-minute window)
  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - issuedAt) > 300) {
    return NextResponse.json({ error: 'SSO token expired' }, { status: 401 });
  }

  // Verify HMAC-SHA256 signature (generated by AiTutor wrapper using MCP_CHAT_SECRET_KEY = AUTH_SECRET)
  const secret = process.env.AUTH_SECRET;
  if (!secret) {
    return NextResponse.json({ error: 'AUTH_SECRET is not configured' }, { status: 500 });
  }

  const expectedSignature = crypto
    .createHmac('sha256', secret)
    .update(subject)
    .digest('hex');

  if (signature !== expectedSignature) {
    return NextResponse.json({ error: 'Invalid SSO token signature' }, { status: 401 });
  }

  try {
    // 3. Look up the user in DB
    const [dbUser] = await db
      .select()
      .from(user)
      .where(eq(user.id, userId))
      .limit(1);

    if (!dbUser) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    // 4. Generate NextAuth v5 JWT token
    //    - Uses AUTH_SECRET and the standard 'authjs.session-token' salt
    //    - Sets id in the token payload so the session callback can populate session.user.id
    const jwtToken = await encode({
      token: {
        id: dbUser.id,
        name: dbUser.email ? dbUser.email.split('@')[0] : '',
        email: dbUser.email,
      },
      secret,
      salt: 'authjs.session-token', // NextAuth v5 default salt
      maxAge: 30 * 24 * 60 * 60, // 30 days
    });

    // 5. Set session cookie (JWT strategy — no DB session record needed)
    const hostHeader =
      request.headers.get('x-forwarded-host') ||
      request.headers.get('host') ||
      'mcp-chat-ait.vercel.app';
    const isHttps =
      request.headers.get('x-forwarded-proto') === 'https' ||
      (!hostHeader.includes('localhost') && !hostHeader.includes('127.0.0.1'));
    const isProduction = process.env.NODE_ENV === 'production' || isHttps;

    // NextAuth v5 uses __Secure- prefix in production
    const cookieName = isProduction
      ? '__Secure-authjs.session-token'
      : 'authjs.session-token';

    const redirectUrl = request.nextUrl.searchParams.get('next') || '/';
    const protocol = isHttps ? 'https' : 'http';
    const response = NextResponse.redirect(new URL(redirectUrl, `${protocol}://${hostHeader}`));

    const maxAgeSecs = 30 * 24 * 60 * 60;
    const expires = new Date(Date.now() + maxAgeSecs * 1000).toUTCString();

    response.headers.append(
      'Set-Cookie',
      `${cookieName}=${jwtToken}; Path=/; HttpOnly; SameSite=Lax; Expires=${expires}${isProduction ? '; Secure' : ''}`
    );

    console.log(`[SSO] User ${dbUser.email} logged in via SSO from ${referer}`);
    return response;
  } catch (err: any) {
    console.error('[SSO] Error:', err);
    return NextResponse.json({ error: err.message || 'Internal Server Error' }, { status: 500 });
  }
}
